Marketplace operators
EmpowerPlastic/empowerchain pull request #1108
Opened 2023-12-18 12:09 UTC by gjermundgaraba

2023-12-19 11:41 UTC, ba1ciu requested changes
Left some points for discussion

2023-12-19 11:41 UTC, ba1ciu commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    if fee_amount.amount > Uint128::from(0u128) {
Does this mean we have to send the crypto payment with the message? Shouldn't we ignore any fee_split if there is one?

2023-12-19 11:41 UTC, ba1ciu commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    let transfer_credits_msg = create_transfer_credits_from_contract_msg(
We'll have to adjust this part as we decided that credits should be auto-retired for the buyer. Right now, it will just transfer the credits to the given account and we won't be able to retire them, no?

And then I guess we should also accept retirererName as a param for release_frozen_credits.

2023-12-20 11:26 UTC, gjermundgaraba commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    if fee_amount.amount > Uint128::from(0u128) {
Not sure what you mean? The point here is to make sure the operator pay the fee (even though the rest of the payment is happening off-chain). The fee should still be paid. If there is not fee-split configured it will be zero of course.

2023-12-20 11:27 UTC, gjermundgaraba commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    let transfer_credits_msg = create_transfer_credits_from_contract_msg(
That is a good point! Will add that.

2023-12-20 12:18 UTC, ba1ciu commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    if fee_amount.amount > Uint128::from(0u128) {
Alright, I get you. It's just, my thinking was that if we're the operator, then we have to pay that fee for ourselves, right?

2023-12-20 12:20 UTC, ba1ciu commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    if fee_amount.amount > Uint128::from(0u128) {
I just wonder if that's the way we should go or maybe do something like a list of addresses not affected by fee_split? Dunno, loud thinking.

2023-12-20 12:24 UTC, gjermundgaraba commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    if fee_amount.amount > Uint128::from(0u128) {
Well, ideally the fee-split will be set up so that the chain gets a small cut of every purchase, in addition to us.

2023-12-20 12:54 UTC, ba1ciu commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    if fee_amount.amount > Uint128::from(0u128) {
Alright, so we indeed gonna need some usdc to pay the fees then.

2023-12-20 12:56 UTC, ba1ciu approved these changes

2023-12-20 15:05 UTC, merged