download certificate
EmpowerPlastic/empowerchain pull request #1139
Opened 2024-01-17 07:41 UTC by PiranavanShanmugavadivelu

2024-01-17 09:49 UTC, ba1ciu reviewed
I'll leave it to @jschill and @portlandnorway

2024-01-17 13:16 UTC, jschill requested changes

2024-01-17 13:16 UTC, jschill commented on frontend/marketplace/src/components/CertificateCard.vue
> +const router = useRoute();
Not used

2024-01-17 13:16 UTC, jschill commented on frontend/marketplace/src/components/CertificateCard.vue
> +const loading = ref(true);
Not used

2024-01-17 13:16 UTC, jschill commented on frontend/marketplace/src/pdfGenerator/pdfGenerator.ts
> +  const doc = new jsPDF("landscape", undefined, undefined, true) as IjsPDF;
Great finding! My pdf decreased from 18.1MB to 1.5MB

2024-01-18 04:48 UTC, jschill approved these changes
👍

2024-01-18 05:51 UTC, merged