Update deps, fix auction detail data, fix google map when coordinates are wrong
EmpowerPlastic/empowerchain pull request #1157
Opened 2024-01-29 13:13 UTC by jschill

This will:
1. Update all deps in `package.json`
2. Make sure auction data is always refetched when going into an auction. This was not the case, it just fetched the data once and if you backed out from the page and go back it wouldnt update. This will hopefully fix a number of issues (such as: https://github.com/EmpowerPlastic/empower-platform/issues/6060 and https://github.com/EmpowerPlastic/empower-platform/issues/6059)
3. Get rid of the nasty Google maps error caused by us passing empty coordinates to vue3-google-maps. (`TypeError: Cannot read properties of null (reading 'fromLatLngToDivPixel')`)

2024-01-29 14:50 UTC, ba1ciu requested changes

2024-01-29 14:50 UTC, ba1ciu commented on frontend/marketplace/src/components/CustomGoogleMap.vue
> +  if ("lat" in obj && "lng" in obj && obj.lat !== 0 && obj.lng !== 0) {
But can't they be 0? Like when someone collects plastics roaming near the [Null Island](https://en.wikipedia.org/wiki/Null_Island)?

2024-01-29 21:40 UTC, jschill commented on frontend/marketplace/src/components/CustomGoogleMap.vue
> +  if ("lat" in obj && "lng" in obj && obj.lat !== 0 && obj.lng !== 0) {
LOL yea you might be right! 
We used two zeros as lat lng default value (`{ lat: 0, lng: 0 }`) in the state before we get real data via apollo. And that makes something to freak out. I have changed this now so default is null which is a more proper value for something that doesn't exist.

2024-01-30 08:42 UTC, ba1ciu approved these changes

2024-01-30 22:03 UTC, merged