fireworks on success page
EmpowerPlastic/empowerchain pull request #1159
Opened 2024-01-30 05:37 UTC by PiranavanShanmugavadivelu

Issue - https://github.com/EmpowerPlastic/empower-platform/issues/5862

2024-01-30 08:56 UTC, ba1ciu approved these changes
I like it :D

2024-01-30 22:41 UTC, jschill commented
Haha lol sweet. I will take a look tomorrow. We have to make sure its possible to click the "See your certificates"-button and that the new lib wont add too much kbs

2024-02-12 21:28 UTC, jschill requested changes
Sorry for late review

2024-02-12 21:28 UTC, jschill commented on frontend/marketplace/src/main.ts
> +app.use(Vue3Lottie);
Can you change from this global use in main.ts to a local use in the component instead? That way we can lazyload this when it's used.

2024-02-14 09:55 UTC, jschill approved these changes
🔥 🚒 🧯 🧨 🧑‍🚒

2024-02-14 16:21 UTC, merged