listing fee tooltip
EmpowerPlastic/empowerchain pull request #1175
Opened 2024-02-08 20:19 UTC by PiranavanShanmugavadivelu

2024-02-09 10:37 UTC, ba1ciu approved these changes

2024-02-09 13:12 UTC, gjermundgaraba commented
Not related to the PR, but so good that we can make these changes so quickly (from idea to done, even if it is pretty small change) 🚀

2024-02-12 21:45 UTC, jschill requested changes
Awesome! But i think we should create a Tooltip-component so we don't accidently use different looks on the tooltips

2024-02-14 09:57 UTC, jschill requested changes

2024-02-14 09:57 UTC, jschill commented on frontend/marketplace/src/components/ui/Tooltip.vue
> +  <p class="tooltip" :data-tip="props.label" data-tip-class="my-custom-tooltip">
Remove data-tip-class?

2024-02-14 09:57 UTC, jschill commented on frontend/marketplace/src/components/ui/Tooltip.vue
> +  iconStyle: string;
Maybe `iconClass` so we know its the class and not the style attribute that we're talking about

2024-02-14 09:57 UTC, jschill commented on frontend/marketplace/src/components/ui/Tooltip.vue
> +  --tooltip-tail: 10px;
Niiiiiice

2024-02-15 07:13 UTC, jschill approved these changes

2024-02-15 07:19 UTC, merged