6008 seo and alignments
EmpowerPlastic/empowerchain pull request #1180
Opened 2024-02-14 10:03 UTC by jschill

- Make sure we use `router-link` when using links so google can crawl
- Fix alignment issues and make sure the whole card is clickable

Alignment issue before:
![Screenshot 2024-02-14 at 11 00 34](https://github.com/EmpowerPlastic/empowerchain/assets/224493/33a204d1-d55e-4155-a5c4-21c0c5e9fe7c)

After:
![Screenshot 2024-02-14 at 11 01 42](https://github.com/EmpowerPlastic/empowerchain/assets/224493/109765f8-cf69-4689-8090-fb9dfd4f4418)

2024-02-16 08:52 UTC, PiranavanShanmugavadivelu requested changes
![image](https://github.com/EmpowerPlastic/empowerchain/assets/28488772/9740e1af-223b-4927-88d1-1c19c7a46112)

Colour changed in `View details ` button

2024-02-16 08:52 UTC, PiranavanShanmugavadivelu commented on frontend/marketplace/src/utils/useListingVolume.ts
> +  console.log("value", value, Math.round(value), Math.round(value) === value);
I think we can remove the console.log()

2024-02-21 12:34 UTC, jschill commented
> ![image](https://private-user-images.githubusercontent.com/28488772/305357032-9740e1af-223b-4927-88d1-1c19c7a46112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTg4MzMsIm5iZiI6MTcwODUxODUzMywicGF0aCI6Ii8yODQ4ODc3Mi8zMDUzNTcwMzItOTc0MGUxYWYtMjIzYi00OTI3LTg4ZDEtMWMxOWM3YTQ2MTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDEyMjg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYjYwOWJjNmE1ODIyMDkwNzE5NzBmYTYwYmNmNjBlMjk4NDVjMDQ0N2E2YzhiMzc3NDhkZDY2NzFiYWQwYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.86WSsqGXHKOLWG8eKZ-R_SYEDGbYwnC57oz7w-Hx1Ik)
> 
> Colour changed in `View details ` button

Button will be removed in another branch so im not fixing that

2024-02-21 15:08 UTC, portlandnorway approved these changes
I see no problem with the route stuff. Green light!

2024-02-21 15:08 UTC, portlandnorway commented on frontend/marketplace/src/router/index.ts
> +  LOGIN_CALLBACK = "login callback",
Only concern is with the spaces in the 2 word route names. Seems unconventional, but if it works, then certainly not a stopper.

2024-02-21 18:00 UTC, jschill commented on frontend/marketplace/src/router/index.ts
> +  LOGIN_CALLBACK = "login callback",
I agree with you on this. My OCD alarm is screaming. Need to solve it.

2024-02-21 21:39 UTC, jschill commented on frontend/marketplace/src/router/index.ts
> +  LOGIN_CALLBACK = "login callback",
Ok i might have over complicated stuff now? But the routes are now snake cased. Please have a look @portlandnorway

2024-02-22 09:37 UTC, jschill commented on frontend/marketplace/src/router/index.ts
> +  LOGIN_CALLBACK = "login callback",
@portlandnorway i cant live with these latest changes, im reverting and will fix this later (promise), but i simply dont really know how to do it without making a mess in typings. Maybe i'll just change the initial enum to kebab-/snake-case, but id like segment to use the same enum... so maybe a simple helper would be enough?

```ts
// snake case the enum
enum PageNames { 
  FAQ = "faq",
  LOGIN_CALLBACK = "login_callback"
  ...
}

// helpers/segment.ts
const toSegment = (pageName: PageNames): string => {
  return pageName.replaceAll('_', ' ')  
}


// used by router
router.push({ name: PageNames.LOGIN_CALLBACK })


// used by segment
analytics.trackPageView(toSegment(PageNames.LOGIN_CALLBACK))

2024-02-22 09:38 UTC, jschill commented on frontend/marketplace/src/router/index.ts
> +  LOGIN_CALLBACK = "login callback",
Yeah i think the above would be enough, but i will add the `toSegment()` function inside the `analytics.trackPageView()` so we don't have to bother manually calling that all the time.

2024-02-22 10:39 UTC, jschill commented on frontend/marketplace/src/router/index.ts
> +  LOGIN_CALLBACK = "login callback",
Thanks for the feedback Dennis and - LOL - making me spend 3 hours on code convention! 😄

2024-02-22 10:40 UTC, jschill commented on frontend/marketplace/src/router/index.ts
> +  LOGIN_CALLBACK = "login callback",
(no i did not spend 3 hours on it)

2024-02-22 10:40 UTC, merged

2024-02-22 13:32 UTC, portlandnorway commented on frontend/marketplace/src/router/index.ts
> +  LOGIN_CALLBACK = "login callback",
Haha this was fun to read, thanks Johannes! I like the conclusion you came to