Rename everything auction to listing or project if its user facing
EmpowerPlastic/empowerchain pull request #1209
Opened 2024-03-03 08:29 UTC by jschill

Rename everything auction to listing internally and if its something a user will see we call it projects

2024-03-03 08:32 UTC, jschill commented on frontend/marketplace/src/router/index.ts
> +      path: "/listings",
Maybe /projects is more appropiate here

2024-03-04 06:28 UTC, PiranavanShanmugavadivelu requested changes

2024-03-04 06:28 UTC, PiranavanShanmugavadivelu commented on frontend/marketplace/src/router/index.ts
> +const Listings = () => import("@/pages/ListingsPage.vue");
It would be better if we use the same naming convention here 
`const ListingsPage = () => import("@/pages/ListingsPage.vue");`

2024-03-04 09:25 UTC, jschill commented on frontend/marketplace/src/router/index.ts
> +const Listings = () => import("@/pages/ListingsPage.vue");
Fixed

2024-03-04 09:31 UTC, PiranavanShanmugavadivelu approved these changes

2024-03-04 10:28 UTC, merged