update applicant implementation, tests, cli
EmpowerPlastic/empowerchain pull request #380
Opened 2022-12-09 13:21 UTC by maheshKRex

2022-12-09 13:58 UTC, gjermundgaraba requested changes

2022-12-09 13:58 UTC, gjermundgaraba commented on chain/proto/empowerchain/plasticcredit/tx.proto
> +  option (cosmos.msg.v1.signer) = "admin";
The signer can be different from the new admin.

Do like the issuer update and have an updater signer.

2022-12-09 13:58 UTC, gjermundgaraba commented on chain/proto/empowerchain/plasticcredit/tx.proto
> +  uint64 applicant_id = 1;
We don't really need to return anything here.

2022-12-09 13:58 UTC, gjermundgaraba commented on chain/x/plasticcredit/client/cli/tx.go
> +			if err := cmd.Flags().Set(flags.FlagFrom, args[0]); err != nil {
Also here you will need to differentiate between admin and --from which might not be the same. So --from will be the "updater".

I do see that this is not set up correctly in update issuer cli also

2022-12-09 13:58 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/applicant.go
> +func (k Keeper) updateApplicant(ctx sdk.Context, applicantId uint64, name string, description string, admin string) error {
This needs to take in the updater and check if the updater is an admin on the applicant.

2022-12-09 13:58 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +		"applicant not found": {
When you add the updater, make sure to add a test to see that only the admin of the applicant (s.sampleApplicantAdmin or something propbably) is allowed to do it.

2022-12-09 13:59 UTC, gjermundgaraba commented
So a few comments and also check the linter and test. You can run them locally with `$ make lint`, `$ make test` and `$make smoketest`

2022-12-12 05:31 UTC, maheshKRex commented on chain/proto/empowerchain/plasticcredit/tx.proto
> +  option (cosmos.msg.v1.signer) = "admin";
added updater signer

2022-12-12 05:31 UTC, maheshKRex commented on chain/proto/empowerchain/plasticcredit/tx.proto
> +  uint64 applicant_id = 1;
fixed

2022-12-12 05:31 UTC, maheshKRex commented on chain/x/plasticcredit/client/cli/tx.go
> +			if err := cmd.Flags().Set(flags.FlagFrom, args[0]); err != nil {
added updater signer, pls check and i'll update update issuer similarly

2022-12-12 05:31 UTC, maheshKRex commented on chain/x/plasticcredit/keeper/applicant.go
> +func (k Keeper) updateApplicant(ctx sdk.Context, applicantId uint64, name string, description string, admin string) error {
added updater signer

2022-12-12 09:08 UTC, gjermundgaraba requested changes
Just some small things :)

2022-12-12 09:08 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/applicant.go
> +func (k Keeper) updateApplicant(ctx sdk.Context, applicantID uint64, name string, description string, admin string, updater sdk.AccAddress) error {
Also not a big deal: but to keep it similar to the other ones I prefer that the updater address comes in as the first argument (after ctx).

so it would be `updateApplicant(ctx, updater, applicantID, etc`

2022-12-12 11:15 UTC, gjermundgaraba requested changes
A couple of things not fixed yet

2022-12-12 11:15 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/applicant.go
> +func (k Keeper) updateApplicant(ctx sdk.Context, applicantID uint64, name string, description string, admin string, updater sdk.AccAddress) error {
This has not been updated yet?

2022-12-12 11:15 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +		"invalid address": {
This is also missing :)

2022-12-12 12:19 UTC, merged