385 update credit class
EmpowerPlastic/empowerchain pull request #390
Opened 2022-12-13 12:31 UTC by maheshKRex

[for ](https://github.com/EmpowerPlastic/empowerchain/issues/385)

2022-12-13 14:55 UTC, gjermundgaraba requested changes

2022-12-13 14:55 UTC, gjermundgaraba commented on chain/proto/empowerchain/plasticcredit/events.proto
> +  string admin = 4 [(cosmos_proto.scalar) = "cosmos.AddressString"];
Should be creator, no?

2022-12-13 14:55 UTC, gjermundgaraba commented on chain/proto/empowerchain/plasticcredit/events.proto
> +  string admin = 4 [(cosmos_proto.scalar) = "cosmos.AddressString"];
And this should be updater

2022-12-13 14:55 UTC, gjermundgaraba commented on chain/proto/empowerchain/plasticcredit/tx.proto
> +  option (cosmos.msg.v1.signer) = "admin";
signer is not admin, but "updater".

2022-12-13 14:55 UTC, gjermundgaraba commented on chain/proto/empowerchain/plasticcredit/tx.proto
> +  string abbreviation = 2;
Actually, you should not be able to change abbreviation or issuer_id. But in the message we do need the abbreviation to know which one to edit. But issuer_id is not necessary here.

2022-12-13 14:55 UTC, gjermundgaraba commented on chain/x/plasticcredit/client/cli/tx.go
> +		Use:   "update-credit-class [abbreviation] [issuer-id] [name]",
Since you can't change issuer-id, it should not be here.

2022-12-13 14:55 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/credit_class.go
> +func (k Keeper) UpdateCreditClass(ctx sdk.Context, updater sdk.AccAddress, abbreviation string, issuerID uint64, name string) error {
Also not send in issuerID here

2022-12-13 14:55 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/credit_class.go
> +	issuer, found := k.GetIssuer(ctx, issuerID)
Instead of doing this, get the credit class first, then get the issuer from the issuer_id in the credit class

2022-12-13 14:55 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/msg_server.go
> +		return nil, errors.Wrapf(sdkerrors.ErrInvalidAddress, "invalid admin address: %s", req.Updater)
invalid updater address, not admin address

2022-12-13 14:55 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +				Name:         "Empower Plastic Credits",
I think this might be the same name as it already has when created, maybe choose something else to make sure it actually changes.

2022-12-13 14:55 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +		"invalid abbreviation": {
Check invalid name also

2022-12-13 14:55 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +func (s *TestSuite) TestUpdateCreditClass() {
Test abbreviation not found cases

2022-12-13 14:55 UTC, gjermundgaraba commented on chain/x/plasticcredit/msgs.go
> +		return errors.Wrapf(sdkerrors.ErrInvalidAddress, "invalid creator address (%s)", err)
updater address

2022-12-13 19:56 UTC, maheshKRex commented on chain/proto/empowerchain/plasticcredit/events.proto
> +  string admin = 4 [(cosmos_proto.scalar) = "cosmos.AddressString"];
yes

2022-12-13 19:56 UTC, maheshKRex commented on chain/proto/empowerchain/plasticcredit/events.proto
> +  string admin = 4 [(cosmos_proto.scalar) = "cosmos.AddressString"];
yes

2022-12-13 19:56 UTC, maheshKRex commented on chain/proto/empowerchain/plasticcredit/tx.proto
> +  string abbreviation = 2;
removed.

2022-12-13 19:57 UTC, maheshKRex commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +func (s *TestSuite) TestUpdateCreditClass() {
checked invalid abbreviation

2022-12-13 21:06 UTC, gjermundgaraba requested changes
A couple of tiny things left! :)

2022-12-13 21:06 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/msg_server.go
> +	admin, err := sdk.AccAddressFromBech32(req.Updater)
updater, not admin

2022-12-13 21:06 UTC, gjermundgaraba commented on chain/x/plasticcredit/msgs.go
> +		return errors.Wrapf(sdkerrors.ErrInvalidAddress, "invalid creator address (%s)", err)
Still says creator here?

2022-12-14 07:05 UTC, gjermundgaraba approved these changes

2022-12-14 07:05 UTC, merged