384 update project
EmpowerPlastic/empowerchain pull request #391
Opened 2022-12-14 08:34 UTC by maheshKRex

2022-12-14 09:44 UTC, ba1ciu approved these changes

2022-12-14 14:00 UTC, gjermundgaraba requested changes

2022-12-14 14:00 UTC, gjermundgaraba commented on chain/x/plasticcredit/msgs.go
> +		return errors.Wrap(sdkerrors.ErrInvalidRequest, "credit class name cannot be empty")
```suggestion
		return errors.Wrap(sdkerrors.ErrInvalidRequest, "project name cannot be empty")
```

2022-12-14 14:01 UTC, gjermundgaraba commented
Looks good @maheshKRex! Just a couple of text updates + 1 more test.

2022-12-15 04:41 UTC, maheshKRex commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +func (s *TestSuite) TestUpdateProject() {
added.

2022-12-15 09:23 UTC, gjermundgaraba approved these changes

2022-12-15 09:23 UTC, merged