Invariants
EmpowerPlastic/empowerchain pull request #397
Opened 2022-12-16 12:08 UTC by ba1ciu

2022-12-16 12:46 UTC, gjermundgaraba commented
@ba1ciu this PR looks like it does not cover: https://github.com/EmpowerPlastic/empowerchain/issues/382 fully

If I read the code correctly we still don't have all the tests in the genesis validation incorporated into invariant checking? Will that be a separate PR (which is fine, but then we need to just unlink 382 from this pr)

2022-12-16 15:02 UTC, ba1ciu commented
@gjermundgaraba Yes, the idea was to merge the base for invariant checking and add the rest later. I unpinned #382.

While we're at it, if we want to use all our genesis validation for invariant checking, which is e.g. checking if credit collection's project id exists in the store, we have to keep in mind that if for some reason state gets corrupted and invariant fails, the chain is halted, so maybe it's not a good idea to make every genesis validation an invariant?

2022-12-16 15:18 UTC, gjermundgaraba commented
> if for some reason state gets corrupted

True, you're right that we need to be careful about it, but at the same time, state corruption sounds like a potentially good reason to halt?

2022-12-17 11:42 UTC, gjermundgaraba requested changes
Looks good! A couple of naming things and some more tests.

2022-12-17 11:42 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/credit.go
> +		if handler(creditCollection) {
The same as the other comment on handler, something with naming here to help understand the return value. Either a better name for the `handler` or name the function `type goodName func....`

2022-12-17 11:42 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/credit.go
> +		if handler(creditBalance) {
Same

2022-12-17 11:42 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/credit_class.go
> +		if handler(creditClass) {
+1

2022-12-17 11:42 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/invariants.go
> +func TotalSupply(k Keeper) sdk.Invariant {
Should probably be renamed to something like TotalSupplyInvariant? The name, which is on the keeper, reads like it returns the total supply.

2022-12-17 11:42 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/invariants_test.go
> +	s.Run("happy path", func() {
Hmm, it would be best if we managed to find a way to actually test an invariant. Might require this package to be `keeper` to get access to low-level setter methods perhaps?

2022-12-17 11:42 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/issuer.go
> +		if handler(issuer) {
+1

2022-12-17 11:42 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/project.go
> +		if handler(project) {
+1

2022-12-19 09:07 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/applicant.go
> +		if handler(applicant) {
As per discussion, we will remove the bool return value from the handler as it is not used right now.

2022-12-19 12:00 UTC, gjermundgaraba approved these changes

2022-12-19 12:11 UTC, merged