e2e tests for project
EmpowerPlastic/empowerchain pull request #414
Opened 2022-12-28 08:12 UTC by maheshKRex

work in progress for create project CLI smoketests, keeping in draft

2022-12-28 08:18 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/tx_test.go
> +				fmt.Println(txResponse.RawLog)
@ba1ciu this still fails to create a new project, even if i tried to use the admin address of the applicant, for --from flag. By looking at the genesis the new Project ID should be 5, but it doesn't find the project.
so i've been trying to trace the output and print RawLog, Body ...but they end up giving the marshalled strings, which i'm not sure unmarshal again like 123A0A342F656D706F776572636. pls help

2022-12-28 09:01 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/tx_test.go
> +				fmt.Println(txResponse.RawLog)
Let's figure it out on Slack.

2022-12-29 08:32 UTC, ba1ciu requested changes

2022-12-29 08:32 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/e2e_test.go
> +			Status:                  plasticcredit.ProjectStatus_SUSPENDED,
Since we're changing the status, can we also change the Name, so it shows that the project is suspended?

2022-12-29 08:32 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/tx_test.go
> +			"6",
Looks unnecessary here?

2022-12-29 08:32 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/tx_test.go
> +			"5",
Not sure, but wouldn't it be more convenient to just use expected state's ID to query the project?

2022-12-29 08:32 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/tx_test.go
> +	admin := "empower1qnk2n4nlkpw9xfqntladh74w6ujtulwnz7rf8m"
I'd fetch it from the keyring by an issuerKey to avoid having raw address here. And same in other tests.

2022-12-29 08:32 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/tx_test.go
> +			[]string{"5", fmt.Sprintf("--%s=%s", flags.FlagFrom, admin)},
I'd avoid using objects created by other tests. We're not sure about the order the test are executed, so it's better to use objects created at genesis level.

2022-12-29 08:32 UTC, ba1ciu commented on chain/x/plasticcredit/keeper/project.go
> +	if project.Status != plasticcredit.ProjectStatus_NEW {
Is there a reason to move this check further down?

2022-12-29 08:32 UTC, ba1ciu commented on chain/x/plasticcredit/keeper/project.go
> +	if project.Status != plasticcredit.ProjectStatus_APPROVED {
As above.

2022-12-29 12:03 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/tx_test.go
> +			"6",
yes, started using expectedState.Id

2022-12-29 12:03 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/tx_test.go
> +			"5",
yes, started using expectedState.Id

2022-12-29 12:03 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/tx_test.go
> +	admin := "empower1qnk2n4nlkpw9xfqntladh74w6ujtulwnz7rf8m"
updated to use issuerKey

2022-12-29 12:03 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/tx_test.go
> +			[]string{"5", fmt.Sprintf("--%s=%s", flags.FlagFrom, admin)},
yeah. added 2 new projects to genesis and made tests independent

2022-12-29 12:03 UTC, maheshKRex commented on chain/x/plasticcredit/keeper/project.go
> +	if project.Status != plasticcredit.ProjectStatus_NEW {
it was i was just trying to test the authorisation check using approved/ rejected projects, instead started using fresh projects, and moved back the checks to where it was before.

2022-12-29 12:07 UTC, ba1ciu commented
> it was i was just trying to test the authorisation check using approved/ rejected projects, instead started using fresh projects, and moved back the checks to where it was before. 

The reason I was asking was that good practice is to perform checks as soon as possible, so failed transactions use least gas possible.

2022-12-29 12:09 UTC, ba1ciu approved these changes

2022-12-29 12:26 UTC, merged