added e2e tests for create, update applicant
EmpowerPlastic/empowerchain pull request #416
Opened 2023-01-03 07:50 UTC by maheshKRex

https://github.com/EmpowerPlastic/empowerchain/issues/408

2023-01-03 08:47 UTC, ba1ciu requested changes
Couple suggestions about other test scenarios, mostly testing all possible transitions between project statuses and one small issue with project update to fix. Those are not specifically for the applicant case, so we can create separate issue for those or fix right away :)

2023-01-03 08:47 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/applicant_tx_test.go
> +		"create applicant": {
We could add the test for empty name (error) and empty description (which should pass) and invalid admin address.

2023-01-03 08:47 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +		"create project": {
Empty name and empty description?

2023-01-03 08:47 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +		"approve project": {
```suggestion
		"approve new project": {
```
Just for clarification

2023-01-03 08:47 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +		"project already approved": {
Maybe let's add approving rejected project also?

2023-01-03 08:47 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +		"project already approved": {
Rejecting already rejected and suspended?

2023-01-03 08:47 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +		"reject project": {
```suggestion
		"reject new project": {
```

2023-01-03 08:47 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +		"suspend project": {
```suggestion
		"suspend approved project": {
```

2023-01-03 08:47 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +		"project already rejected": {
Suspending already suspended and new projects?

2023-01-03 08:47 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +			&plasticcredit.Project{
Project with ID 3 is used for both update and approve testing. You should use different for each case. We should keep in mind that the test should run successfully both as a whole suite and independently. If you run just this test, it will fail, because Project 3 is initially in new state.

2023-01-04 18:09 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/applicant_tx_test.go
> +		"create applicant": {
@ba1ciu i've been struggling with the invalid admin test for create applicant. Similarly to other invalid admin tests i tried to provide a test case with simply an other address string as the admin account address instead of issuer/applicant address from keyring. 
`"invalid admin address": {
			[]string{"empower1qnk2n4nlkpw9xfqntladh74w6ujtulwnz7rf", "New", "Grab that bottle", fmt.Sprintf("--%s=%s", flags.FlagFrom,issuerKey.Name)},
		`
But the clitestutil.ExecTestCLICmd fails to pass this string to the test with error key not found, so when invoking the CLI this way, does is always need to have a valid key AccAddress, like issuer / applicant key address?
`empower1qnk2n4nlkpw9xfqntladh74w6ujtulwnz7rf8.info: key not found`

2023-01-05 02:08 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/applicant_tx_test.go
> +		"create applicant": {
found that this is imposed by validation check at CLI x/plasticcredit/client/cli/tx.go forcing to take --from addr as the Admin, making it to always have a valid AccAddress. So it can be any address as we don't restrict anybody with a signing address to go ahead and create an applicant.
`if err := cmd.Flags().Set(flags.FlagFrom, args[0]); err != nil {
	return err
}`
So should we still do an invalid admin test, or just test for validity of from address.

2023-01-05 07:45 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +		"create project": {
added.

2023-01-05 07:50 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +			&plasticcredit.Project{
agree. updated to use new project for this. https://github.com/EmpowerPlastic/empowerchain/blob/702dbf9b8b0940edd69e170941155eba76c195ba/chain/tests/e2e/plasticcredit/project_tx_test.go#L104

2023-01-05 07:51 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +		"project already rejected": {
added.

2023-01-05 07:51 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +		"project already approved": {
added.

2023-01-06 11:36 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/applicant_tx_test.go
> +		"create applicant": {
I think we should leave validation in tx.go as it is, so the cli works both with addresses and key names.
If the message signer is an admin and therefore you cannot give anyone other than yourself an admin role, then I suggest we either drop the admin param and take it from the --from flag or allow to assign admin to others by adding a creator field, which will hold the address from --from. Wdyt, @gjermundgaraba?

2023-01-06 14:34 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/applicant_tx_test.go
> +		"create applicant": {
yes, updated create-applicant to take admin using --from flag, and it looks much neater.

2023-01-07 16:59 UTC, ba1ciu approved these changes

2023-01-08 04:38 UTC, merged