e2e tests for issue credits, transfer credits updated
EmpowerPlastic/empowerchain pull request #447
Opened 2023-01-25 05:26 UTC by maheshKRex

2023-01-25 10:48 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/credits_tx_test.go
> +				s.Require().NoError(s.network.WaitForNextBlock())
`WaitForNextBlock()` is redundant before `getCliResponse()` as the latter also waits for next blocks.

2023-01-25 10:49 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/credits_tx_test.go
> +				s.Require().NoError(s.network.WaitForNextBlock())
Same as in the previous `case` statement.

2023-01-25 10:49 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +				s.Require().NoError(s.network.WaitForNextBlock())
Same.

2023-01-25 10:50 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/credits_tx_test.go
> +				s.Require().NoError(s.network.WaitForNextBlock())
Same.

2023-01-25 11:22 UTC, gjermundgaraba requested changes

2023-01-25 11:22 UTC, gjermundgaraba commented on chain/tests/e2e/plasticcredit/credits_tx_test.go
> +			[]string{"1", "456", "1000", fmt.Sprintf("--%s=%s", flags.FlagFrom, issuerKey.Name)},
I would strongly prefer that we declare the name of each argument in the struct literals. I didn't realize how hard it was to read because I've been mostly seeing these tests in IntelliJ which shows me the name of each inline.

So add `args: []string.....`, etc.
Perhaps you can just do the same for all the tests while you're at it. If you prefer to split that up we can create a separate task for it. Up to you.

2023-01-26 11:57 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/credits_tx_test.go
> +				s.Require().NoError(s.network.WaitForNextBlock())
fixed.

2023-01-26 11:57 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/project_tx_test.go
> +				s.Require().NoError(s.network.WaitForNextBlock())
fixed.

2023-01-26 11:57 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/credits_tx_test.go
> +				s.Require().NoError(s.network.WaitForNextBlock())
fixed.

2023-01-26 11:58 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/credits_tx_test.go
> +			[]string{"1", "456", "1000", fmt.Sprintf("--%s=%s", flags.FlagFrom, issuerKey.Name)},
yeah agree. i just cleaned up for credits related new e2e tests, will do the same for others.

2023-01-26 13:43 UTC, gjermundgaraba commented on chain/tests/e2e/plasticcredit/credits_tx_test.go
> +			[]string{"1", "456", "1000", fmt.Sprintf("--%s=%s", flags.FlagFrom, issuerKey.Name)},
Great, created a separate issue to track it so we can merge this: https://github.com/EmpowerPlastic/empowerchain/issues/452

2023-01-26 13:43 UTC, gjermundgaraba approved these changes

2023-01-27 15:04 UTC, ba1ciu approved these changes

2023-01-28 11:43 UTC, merged