479 hash file
EmpowerPlastic/empowerchain pull request #529
Opened 2023-03-06 07:59 UTC by PiranavanShanmugavadivelu

Hash file page and create proof page designs and functions are completed.

2023-03-06 08:19 UTC, gjermundgaraba requested changes

2023-03-06 08:19 UTC, gjermundgaraba commented on frontend/proof-of-existence/src/App.vue
> +              <svg
Could we please try to keep SVG's in separate files so they don't clutter up the HTML so much?

2023-03-06 08:19 UTC, gjermundgaraba commented on frontend/proof-of-existence/src/assets/main.css
> +/*@import './base.css';*/
Let's delete commented out code

2023-03-06 08:19 UTC, gjermundgaraba commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +  console.log(e.target?.files[0].name);
Let's get rid of console.log's

2023-03-06 08:19 UTC, gjermundgaraba commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +            <!--            <div class="w-full bg-lightBlack rounded-full mb-2 mt-2">-->
Unless we actually need this I would ask to delete commented out code

2023-03-06 08:30 UTC, gjermundgaraba requested changes
The `npm run build` command does not run.

2023-03-06 08:30 UTC, gjermundgaraba commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +import { Tabs } from "flowbite";
Are there some unused variables here?

2023-03-06 08:30 UTC, gjermundgaraba commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +const activeTab = ref("first");
Some of these are also unused I believe? If so, please remove them.

2023-03-06 09:01 UTC, PiranavanShanmugavadivelu commented
Changes done and commited

2023-03-06 09:19 UTC, gjermundgaraba requested changes

2023-03-06 09:19 UTC, gjermundgaraba commented on frontend/proof-of-existence/src/App.vue
> +              <svg
And this one

2023-03-06 09:19 UTC, gjermundgaraba commented on frontend/proof-of-existence/src/App.vue
> +              <svg
This one still here

2023-03-06 09:28 UTC, PiranavanShanmugavadivelu commented
Changes completed

2023-03-06 09:38 UTC, gjermundgaraba commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +const activeTab = ref("first");
Can you look at the unused variables here too please?

2023-03-06 09:39 UTC, jschill commented on frontend/proof-of-existence/src/App.vue
> +import "flowbite";
Do we need to import flowbite? I'm not familiar with that lib so maybe thats common practice, but i'm not sure bundlers can tree shake it when done like this?

2023-03-06 09:40 UTC, gjermundgaraba commented
`npm run build` does not work still

2023-03-06 09:40 UTC, jschill commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +    let reader = new FileReader();
`reader` is not reassigned, so you can switch `let` for `const`

2023-03-06 09:42 UTC, jschill commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +async function hashFile(file: File) {
Mixing of arrow-functions vs named functions. Is that intentional?

2023-03-06 09:58 UTC, jschill commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +  file.value = e.target.files[0];
Type mismatch. e is the event.

```suggestion
const handleFileUpload = async (e: Event) => {
  const target = e.target as HTMLInputElement;
  const targetFiles = target.files;
  const hasTargetFiles = Array.isArray(targetFiles) && targetFiles.length > 0;
  fileName.value = hasTargetFiles ? targetFiles[0].name : defaultFilename;
  file.value = hasTargetFiles ? targetFiles[0] : undefined;
```

2023-03-06 10:02 UTC, jschill commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +const fileName = ref("choose file");
Do we need to save the `fileName` since we have the `file` already with the name in it? If we want this to be "choose file" if file is undefined we can change this to a computed value instead?

2023-03-06 10:04 UTC, jschill commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +const hashing = ref(false);
What is `hashing` used for? I see its toggled between true and false but we're not using the value anywhere?

2023-03-06 10:05 UTC, jschill commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +    reader.addEventListener("loadend", (e) => resolve(e.target.result));
`e.target` can be null

2023-03-06 10:06 UTC, jschill commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +  console.log(result);
console.log

2023-03-06 10:10 UTC, jschill commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +  file.value = e.target.files[0];
(if above is accepted, dont forget to set `const defaultFilename = 'choose file'` somewhere above)

2023-03-07 08:19 UTC, PiranavanShanmugavadivelu commented on frontend/proof-of-existence/src/App.vue
> +import "flowbite";
I checked with this. But when I removed Flowbite import, Flowbite components are not working properly.

2023-03-07 08:24 UTC, PiranavanShanmugavadivelu commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +  file.value = e.target.files[0];
I did this change, But to this line  " const hasTargetFiles = Array.isArray(targetFiles) && targetFiles.length > 0;", targetFiles are not an array. I think it is an Object

2023-03-07 14:00 UTC, gjermundgaraba approved these changes

2023-03-07 14:00 UTC, merged