Update listing
EmpowerPlastic/empowerchain pull request #549
Opened 2023-03-15 14:57 UTC by ba1ciu

2023-03-16 09:26 UTC, gjermundgaraba requested changes

2023-03-16 09:26 UTC, gjermundgaraba commented on chain/tests/e2e/marketplace/update_listing_test.go
> +func (s *E2ETestSuite) TestUpdateListing() {
I prefer to keep the e2e tests lighter and only test the things that can't be unit-tested directly in rust. These tests are very slow to run, after all.

Many of these tests seem redundant, given that they also exist in the unit tests, right?

2023-03-16 09:26 UTC, gjermundgaraba commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    if (LISTINGS.may_load(deps.storage, (info.sender.clone(), denom.clone()))?).is_some() {
Can you add a unit test that covers this scenario?

2023-03-16 09:26 UTC, gjermundgaraba commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +        .add_attribute("listing_owner", info.sender)
Probably denom would be a good idea to add here too?

2023-03-16 09:26 UTC, gjermundgaraba commented on cosmwasm/contracts/plastic-credit-marketplace/src/query.rs
> +        QueryMsg::Listing {owner, denom} => to_binary(&listing(deps, owner, denom)?),
Maybe at least a simple unit test for this one too (not found + found)

2023-03-16 09:49 UTC, ba1ciu commented on chain/tests/e2e/marketplace/update_listing_test.go
> +func (s *E2ETestSuite) TestUpdateListing() {
> I prefer to keep the e2e tests lighter and only test the things that can't be unit-tested directly in rust. These tests are very slow to run, after all.
> 
> Many of these tests seem redundant, given that they also exist in the unit tests, right?

Agreed. In that case I'd only keep 2 first tests as there are actual plastic credit transfers being made there. Makes sense? @gjermundgaraba

2023-03-16 10:43 UTC, gjermundgaraba commented on chain/tests/e2e/marketplace/update_listing_test.go
> +func (s *E2ETestSuite) TestUpdateListing() {
Yes, that makes perfect sense :+1:

2023-03-16 10:43 UTC, gjermundgaraba commented on chain/tests/e2e/marketplace/update_listing_test.go
> +func (s *E2ETestSuite) TestUpdateListing() {
Off-topic for this PR, but maybe we should do this for all our other e2e tests too. See which ones are actually redundant. They are getting _veeeery_ slow and heavy now.

2023-03-17 08:41 UTC, ba1ciu commented on chain/tests/e2e/marketplace/update_listing_test.go
> +func (s *E2ETestSuite) TestUpdateListing() {
Agreed! Let's follow it [here](https://github.com/EmpowerPlastic/empowerchain/issues/559)!

2023-03-18 12:14 UTC, gjermundgaraba approved these changes

2023-03-18 13:02 UTC, merged