cleaned up e2e tests
EmpowerPlastic/empowerchain pull request #574
Opened 2023-03-24 08:19 UTC by maheshKRex

https://github.com/EmpowerPlastic/empowerchain/issues/559

2023-03-27 09:18 UTC, ba1ciu requested changes

2023-03-27 09:18 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/applicant_tx_test.go
> -		"wrong signer": {
We should add an integration test with a wrong signer, but one that will pass bech32 validation.

2023-03-27 09:18 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/issuer_tx_test.go
> -func (s *E2ETestSuite) TestCmdCreateIssuer() {
I'd leave issuer creation with gov. We don't have that covered on the integration level.

2023-03-27 09:18 UTC, ba1ciu commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +func (s *TestSuite) TestUpdateIssuerCreator() {
It's the same as `TestCreateIssuer`?

2023-03-27 10:13 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/applicant_tx_test.go
> -		"wrong signer": {
yes, having this in msg_server_tests, here sample.AccAddress generates some valid address, but not authorised to sign.
`"unauthorized caller / wrong signer": {
			msg: &plasticcredit.MsgUpdateApplicant{
				Updater:     sample.AccAddress(), 
				ApplicantId: 1,
				Name:        "Empower",
				Description: "Empower is cool",
				Admin:       issuerAdmin,
			},
			err: sdkerrors.Er`

2023-03-27 13:35 UTC, maheshKRex commented on chain/tests/e2e/plasticcredit/issuer_tx_test.go
> -func (s *E2ETestSuite) TestCmdCreateIssuer() {
agree. reverted the removal.

2023-03-27 13:35 UTC, maheshKRex commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +func (s *TestSuite) TestUpdateIssuerCreator() {
nice catch. removed them.

2023-03-27 13:46 UTC, ba1ciu requested changes

2023-03-27 13:46 UTC, ba1ciu commented on chain/tests/e2e/plasticcredit/issuer_tx_test.go
> +func (s *E2ETestSuite) TestCmdUpdateIssuer() {
Updates we can get rid of I think as those are done by sending a standard message and leave only creates as they use `NewCmdSubmitProposal()`?

2023-03-28 10:04 UTC, ba1ciu approved these changes

2023-03-28 10:04 UTC, merged