458 rename credit class to credit type
EmpowerPlastic/empowerchain pull request #580
Opened 2023-03-30 14:08 UTC by maheshKRex

renaming all occurences of Credit Class with Credit Type in code [](https://github.com/EmpowerPlastic/empowerchain/issues/458)

2023-03-31 07:21 UTC, ba1ciu requested changes

2023-03-31 07:21 UTC, ba1ciu commented on chain/proto/empowerchain/plasticcredit/events.proto
>  // EventProjectApproved is an event emitted when a project is approved by the issuer associated with the projects credit class
This one and some other comments also need refactoring.

2023-03-31 07:21 UTC, ba1ciu commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +		"invalid name": {
Isn't this a part of message validation and not integration test?

2023-03-31 07:21 UTC, ba1ciu commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +		"empty serial number": {
Same here? Message validation or should we leave it here?

2023-03-31 07:21 UTC, ba1ciu commented on chain/x/plasticcredit/simulation/operations.go
>  			return simtypes.NoOpMsg(plasticcredit.ModuleName, msgType, "not enough balance to create credit class"), nil, nil
Err message to refactor.

2023-03-31 07:21 UTC, ba1ciu commented on chain/x/plasticcredit/simulation/operations.go
>  			return simtypes.NoOpMsg(plasticcredit.ModuleName, msgType, "unable to get credit class"), nil, nil
Err message to refactor.

2023-03-31 07:21 UTC, ba1ciu commented on chain/x/plasticcredit/simulation/operations.go
>  			return simtypes.NoOpMsg(plasticcredit.ModuleName, msgType, "unable to get credit class"), nil, nil
Err message to refactor.

2023-03-31 07:21 UTC, ba1ciu commented on chain/x/plasticcredit/simulation/operations.go
>  			return simtypes.NoOpMsg(plasticcredit.ModuleName, msgType, "unable to get credit class"), nil, nil
And some others below

2023-03-31 12:24 UTC, maheshKRex commented on chain/x/plasticcredit/keeper/msg_server_test.go
> +		"invalid name": {
yeah, i messed up while resolving merge conflicts with too many files :) , removed all the added back tests there.

2023-03-31 12:35 UTC, maheshKRex commented on chain/x/plasticcredit/simulation/operations.go
>  			return simtypes.NoOpMsg(plasticcredit.ModuleName, msgType, "unable to get credit class"), nil, nil
updated Err message

2023-03-31 12:35 UTC, maheshKRex commented on chain/x/plasticcredit/simulation/operations.go
>  			return simtypes.NoOpMsg(plasticcredit.ModuleName, msgType, "unable to get credit class"), nil, nil
Updated err messages

2023-04-04 07:52 UTC, ba1ciu approved these changes

2023-04-04 08:14 UTC, merged