added cancel listing and tests
EmpowerPlastic/empowerchain pull request #587
Opened 2023-04-05 07:51 UTC by maheshKRex

implementation for [](https://github.com/EmpowerPlastic/empowerchain/issues/556)

2023-04-05 08:39 UTC, gjermundgaraba requested changes

2023-04-05 08:39 UTC, gjermundgaraba commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    // Zero credits means the listing is already cancelled
If I am wrong, please add a test that hits this path.

2023-04-05 08:39 UTC, gjermundgaraba commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +            assert_eq!(listing.unwrap_err(), ContractError::ListingNotFound {});
Maybe also try to cancel the listing again and verify that you get ListingNotFound

2023-04-05 08:39 UTC, gjermundgaraba commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +            execute(deps.as_mut(), mock_env(), creator_info.clone(), cancel_listing_msg).unwrap();
Check the attributes and messages sent by this (should be similar in other messages we have)

2023-04-05 08:39 UTC, gjermundgaraba commented on chain/tests/e2e/marketplace/cancel_listing_test.go
> +			if tc.expectedErr {
And since we don't have any scenarios where we really need this, we can just remove the the `if` here :)

2023-04-06 06:42 UTC, maheshKRex commented on chain/tests/e2e/marketplace/cancel_listing_test.go
> +	for name, tc := range testCases {
dropped the table, and also updated this to check owners credit balance, after cancel listing.

2023-04-06 06:45 UTC, maheshKRex commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    // Zero credits means the listing is already cancelled
yes, added a test and when the listing is already cancelled it returns listing not found. So since the buy credits function cleans up any listing reaching a zero balance, and if there is no other user case to bring the balance to zero, this check may never get executed. should i remove it @gjermundgaraba

2023-04-06 06:46 UTC, maheshKRex commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +            assert_eq!(listing.unwrap_err(), ContractError::ListingNotFound {});
added test.

2023-04-06 06:46 UTC, maheshKRex commented on chain/tests/e2e/marketplace/cancel_listing_test.go
> +			if tc.expectedErr {
removed.

2023-04-06 07:00 UTC, gjermundgaraba commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    // Zero credits means the listing is already cancelled
Yeah, it seems like it should not be possible, so can remove it then :+1:

2023-04-06 07:47 UTC, ba1ciu requested changes

2023-04-06 07:47 UTC, ba1ciu commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +        LISTINGS.remove(deps.storage, (Addr::unchecked(owner.clone()), denom.clone()));
If the credit balance reaches zero during the purchase, we have two storage operations, first to save the updated listing and then delete it with the next one. I assume it might not be very gas-efficient that way? Maybe let's use `if else` and perform update if the balance is gt 0 and delete if it's 0?

2023-04-06 07:47 UTC, ba1ciu commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +        fn test_cancel_listing_by_non_owner() {
This one looks incomplete. Also, there's no such thing as canceling by a non-owner, as we don't pass the owner address ourselves, so the test actually becomes same as `test_cancel_listing_that_does_not_exist`

2023-04-06 07:47 UTC, ba1ciu commented on chain/tests/e2e/marketplace/cancel_listing_test.go
> +		"PTEST/UPDATE_LISTING_1",
Please use a separate credit collection for the test. It's gonna fail randomly if the execution order of this one and update listing changes.

2023-04-06 07:47 UTC, ba1ciu commented on chain/tests/e2e/marketplace/cancel_listing_test.go
> +	creditOwnerBalanceBefore := s.GetCreditBalance(e2e.ApplicantAddress, "PTEST/00001")
The balance before here is taken after the listing creation, so the user should have less credits, but it's compared to balance after, which is balance after the listing has been canceled. Doesn't seem right or am I mistaken?

2023-04-06 08:28 UTC, maheshKRex commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +        fn test_cancel_listing_by_non_owner() {
yeah, you got me using copilot too much, will remove it.

2023-04-07 08:14 UTC, maheshKRex commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +    // Zero credits means the listing is already cancelled
removed.

2023-04-07 08:14 UTC, maheshKRex commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +            execute(deps.as_mut(), mock_env(), creator_info.clone(), cancel_listing_msg).unwrap();
added checks.

2023-04-07 08:14 UTC, maheshKRex commented on cosmwasm/contracts/plastic-credit-marketplace/src/execute.rs
> +        LISTINGS.remove(deps.storage, (Addr::unchecked(owner.clone()), denom.clone()));
yes, makes sense. added conditional.

2023-04-07 08:15 UTC, maheshKRex commented on chain/tests/e2e/marketplace/cancel_listing_test.go
> +		"PTEST/UPDATE_LISTING_1",
added a new collection.

2023-04-07 08:17 UTC, maheshKRex commented on chain/tests/e2e/marketplace/cancel_listing_test.go
> +	creditOwnerBalanceBefore := s.GetCreditBalance(e2e.ApplicantAddress, "PTEST/00001")
yes, was using the e2e.ApplicantAddress instead of using the owner's address , and i think that made it to return matching balance, not the deducted one. updated to capture balance before create listing and use correct address for both queries.

2023-04-10 08:53 UTC, gjermundgaraba approved these changes

2023-04-10 08:54 UTC, merged