Local containerized empowerchain node
EmpowerPlastic/empowerchain pull request #588
Opened 2023-04-05 09:31 UTC by ba1ciu

2023-04-05 09:52 UTC, gjermundgaraba commented
It might not be important, or even useful, but you could have done this in an Earthfile too - if you wanted to

2023-04-06 12:38 UTC, gjermundgaraba requested changes

2023-04-06 12:38 UTC, gjermundgaraba commented on .github/workflows/devnet_push.yml
> +      - name: push image
You could do most of this in automatically in the earthfile when using `earhtly --push +devnet`. Check out the empower-platform Earthfiles to see some examples.

2023-04-06 12:38 UTC, gjermundgaraba commented on .github/workflows/devnet_push.yml
> +      - name: push image
https://github.com/EmpowerPlastic/empower-platform/blob/6181e9c1123d28e7dfe6864334a61ad088cd2900/.github/workflows/pipeline-be-user.yml#L106

2023-04-06 12:38 UTC, gjermundgaraba commented on .github/workflows/devnet_push.yml
> +      - name: push image
And you can have multiple tags in a single save image: https://github.com/EmpowerPlastic/empower-platform/blob/6181e9c1123d28e7dfe6864334a61ad088cd2900/general/backend/cloud-run-user/Earthfile#L21

2023-04-06 12:38 UTC, gjermundgaraba commented on .github/workflows/devnet_push.yml
> +      - name: push image
(Even if you add --push inside the Earthfile, it will not try to push unless you also add --push to the earthly command)

2023-04-06 12:50 UTC, ba1ciu commented on .github/workflows/devnet_push.yml
> +      - name: push image
Cool! Will use that

2023-04-07 08:14 UTC, ba1ciu commented
Temporarily closing PR to not spam with actions

2023-04-11 07:21 UTC, merged