561 on chain certificates
EmpowerPlastic/empowerchain pull request #624
Opened 2023-04-20 08:44 UTC by maheshKRex

certificates as an on-chain module [task](https://github.com/EmpowerPlastic/empowerchain/issues/561)

2023-04-20 13:12 UTC, gjermundgaraba requested changes

2023-04-20 13:12 UTC, gjermundgaraba commented on chain/proto/empowerchain/certificates/query.proto
> +message QueryCertificateRequest {
I don't remember if we talked about queries for this module. If it is needed the query seems to be missing elsewhere too.

2023-04-20 13:12 UTC, gjermundgaraba commented on chain/x/certificates/client/cli/tx.go
> +var DefaultRelativePacketTimeoutTimestamp = uint64((time.Duration(10) * time.Minute).Nanoseconds())
What is this for?

2023-04-20 13:12 UTC, gjermundgaraba commented on chain/x/certificates/client/cli/tx.go
> +	// this line is used by starport scaffolding # 1
Remove all of these comments

2023-04-20 13:12 UTC, gjermundgaraba commented on chain/x/certificates/genesis.go
> +			return errors.Wrapf(ErrCertificateDuplicate, "duplicate issuer with id %d was found", certificate.Id)
Not duplicate issuer, but duplicate certificate?

2023-04-20 13:12 UTC, gjermundgaraba commented on chain/x/certificates/genesis_test.go
> +		err  bool
Maybe do the same as in plasticcredit genesis state test and check for the actual error (or nil). That, and instead of doing "name", do testCases := map[string]struct {

2023-04-20 13:12 UTC, gjermundgaraba commented on chain/x/certificates/keys.go
> +func CreateCertificateKey(owner sdk.AccAddress, id uint64) ([]byte, error) {
Instead of returning an error, just do what we do in plastic credit:
owner = address.MustLengthPrefix(owner)
That way you don't need to check the error everywhere

2023-04-20 13:12 UTC, gjermundgaraba commented on chain/x/certificates/module/module.go
> +// RegisterInvariants registers the invariants of the module. If an invariant deviates from its predicted value, the InvariantRegistry triggers appropriate logic (most often the chain will be halted)
delete

2023-04-24 08:55 UTC, ba1ciu requested changes

2023-04-24 08:55 UTC, ba1ciu commented on chain/x/certificates/keeper/certificate.go
> +func (k Keeper) GetAllCertificatesByOwner(ctx sdk.Context, owner sdk.AccAddress, pageReq query.PageRequest) ([]certificates.Certificate, query.PageResponse, error) {
`owner` is unused. We're iterating through every certificate in the store here. Not sure if it will work, but I'd try to fetch the certificate store by using a compound key of `<certificate_store, owner>`, then we should get results only for a given user. So we would to create a store key using function like [this one](https://github.com/EmpowerPlastic/empowerchain/blob/faba9f307b71f9fd7e23a7a1d4e6d2fe6f8e269b/chain/x/plasticcredit/keys.go#L47).

2023-04-24 08:55 UTC, ba1ciu commented on chain/x/certificates/keeper/msg_server.go
> +		if len(issuer) == 0 || sdk.AccAddress(issuer).Empty() {
If we want to verify if it's a correct bech32 address, we should use `sdk.AccAddressFromBech32()`. `sdk.AccAddress()` expects public key and not bech32 address.

2023-04-24 08:55 UTC, ba1ciu commented on chain/x/certificates/keeper/msg_server_test.go
> +			msg: &certificates.MsgCreateCertificate{
I guess we might not want to allow `data` field to be empty. @gjermundgaraba ?

2023-04-26 08:25 UTC, maheshKRex commented on chain/x/certificates/client/cli/tx.go
> +	// this line is used by starport scaffolding # 1
removed

2023-04-26 08:25 UTC, maheshKRex commented on chain/x/certificates/genesis.go
> +			return errors.Wrapf(ErrCertificateDuplicate, "duplicate issuer with id %d was found", certificate.Id)
fixed.

2023-04-26 08:26 UTC, maheshKRex commented on chain/x/certificates/genesis_test.go
> +		err  bool
updated.

2023-04-26 08:27 UTC, maheshKRex commented on chain/x/certificates/keys.go
> +func CreateCertificateKey(owner sdk.AccAddress, id uint64) ([]byte, error) {
fixed.

2023-04-26 08:27 UTC, maheshKRex commented on chain/x/certificates/simulation/simap.go
> +func FindAccount(accs []simtypes.Account, address string) (simtypes.Account, bool) {
need to add simulation tests here, holding it until other priorities are fixed.

2023-04-26 08:28 UTC, maheshKRex commented on chain/x/certificates/client/cli/tx.go
> +var DefaultRelativePacketTimeoutTimestamp = uint64((time.Duration(10) * time.Minute).Nanoseconds())
removed.

2023-04-26 08:30 UTC, maheshKRex commented on chain/x/certificates/module/module.go
> +// RegisterInvariants registers the invariants of the module. If an invariant deviates from its predicted value, the InvariantRegistry triggers appropriate logic (most often the chain will be halted)
added invariant for IDCounter.

2023-04-27 03:32 UTC, maheshKRex commented on chain/app/app.go
@gjermundgaraba @ba1ciu i'm getting an error on building the empowerd binary (the binary just report Error:  <nil>
on every command), on this branch, and it got something to do with the certificates module. 
- I basically added certificate module related entry in app.go, for every such module/keeper related entry done for plasticcredits.
- Or could it be an issue coming from /certificates/module.go, which is again i followed what we did for platiccredits.

2023-04-28 08:13 UTC, maheshKRex commented on chain/x/certificates/keeper/certificate.go
> +func (k Keeper) GetAllCertificatesByOwner(ctx sdk.Context, owner sdk.AccAddress, pageReq query.PageRequest) ([]certificates.Certificate, query.PageResponse, error) {
fixed, by storing by owners in the KV store.

2023-04-28 08:28 UTC, maheshKRex commented on chain/app/app.go
fixed with help of jakub, culprit was client/tx.go

2023-04-28 09:30 UTC, gjermundgaraba commented on chain/x/certificates/keeper/msg_server_test.go
> +			msg: &certificates.MsgCreateCertificate{
Yeah, makes sense

2023-04-28 11:12 UTC, maheshKRex commented on chain/x/certificates/keeper/msg_server.go
> +		if len(issuer) == 0 || sdk.AccAddress(issuer).Empty() {
updated.

2023-04-28 11:12 UTC, maheshKRex commented on chain/x/certificates/keeper/msg_server_test.go
> +			msg: &certificates.MsgCreateCertificate{
made it required field, updates validations.

2023-04-28 11:12 UTC, maheshKRex commented on chain/x/certificates/msgs.go
> +	owner, err := sdk.AccAddressFromBech32(m.Owner)
fixed.

2023-04-28 11:13 UTC, maheshKRex commented on chain/x/certificates/types.go
> +func (cert Certificate) AddressHasAuthorization(addr sdk.AccAddress) bool {
removed.

2023-05-03 14:13 UTC, maheshKRex commented on chain/x/certificates/client/cli/tx.go
> +		Use:   "create-certificate [certificate-type] [certificate-owner] [certificate-issuer] [map of certificate attributes]",
added.

2023-05-04 08:56 UTC, gjermundgaraba requested changes

2023-05-04 08:56 UTC, gjermundgaraba commented on chain/x/certificates/genesis.go
> +func (gs GenesisState) Validate() error {
It looks like we do, right?

2023-05-04 08:56 UTC, gjermundgaraba commented on chain/x/certificates/genesis.go
> +func (gs GenesisState) Validate() error {
Oh no, it says some of the error are never hit, maybe we need some more test cases to hit those too?

2023-05-04 08:56 UTC, gjermundgaraba commented on chain/x/certificates/keeper/certificate.go
> +func (k Keeper) CreateCertificateInternal(ctx sdk.Context, req *certificates.MsgCreateCertificate) (uint64, error) {
why is the "internal" method public, while the other is private?

2023-05-04 08:56 UTC, gjermundgaraba commented on chain/x/certificates/keeper/certificate.go
> +func (k Keeper) CreateCertificateInternal(ctx sdk.Context, req *certificates.MsgCreateCertificate) (uint64, error) {
In either case, maybe we can rename to better describe their difference?

2023-05-04 11:11 UTC, ba1ciu requested changes

2023-05-04 11:11 UTC, ba1ciu commented on chain/x/certificates/client/cli/tx.go
> +		Use:   "create-certificate [map of certificate attributes]",
So are we reading certificate data from the file? If yes we should change cmd description and use absolute path

2023-05-04 11:11 UTC, ba1ciu commented on chain/scripts/test/testdata/certificate_update_params.json
> +        "allowed_issuer": [
Are we chainging this to just one issuer or why is this change made?

2023-05-04 11:13 UTC, ba1ciu commented on chain/proto/empowerchain/certificates/query.proto
> +    option (google.api.http).get = "/EmpowerPlastic/empowerchain/certificates/{id}/{owner}";
I agree. Pagination params should be in a request object and not query param.

2023-05-05 20:09 UTC, maheshKRex commented on chain/scripts/test/testdata/certificate_update_params.json
> +        "allowed_issuer": [
looks like was mistaken set as "issuers" before, anyway now reverted back to "issuers" after renaming at types proto def.

2023-05-05 20:09 UTC, maheshKRex commented on chain/x/certificates/client/cli/tx.go
> +		Use:   "create-certificate [map of certificate attributes]",
updated to read from file

2023-05-05 20:10 UTC, maheshKRex commented on chain/x/certificates/module/module.go
> +	ak certificates.AccountKeeper,
removed.

2023-05-05 20:10 UTC, maheshKRex commented on chain/x/certificates/expected_keepers.go
> +type AccountKeeper interface {
removed.

2023-05-05 20:19 UTC, maheshKRex commented on chain/x/certificates/keeper/certificate.go
> +func (k Keeper) CreateCertificateInternal(ctx sdk.Context, req *certificates.MsgCreateCertificate) (uint64, error) {
when directly calling the keeper function createCertificate from plastic credits: retire credits, we discussed to skip the checks on allowed issuers, as the calling context of plastic credits does not have the allowed issuers params set. Just renamed this to CreateCertificateViaInternalModule, and it's going to be called from another module, so had to make it public. While the other function createCertificates with the allowed issuer check is used by certificates msg_server.

2023-05-05 20:19 UTC, maheshKRex commented on chain/x/certificates/genesis.go
> +func (gs GenesisState) Validate() error {
added

2023-05-05 20:19 UTC, maheshKRex commented on chain/x/certificates/client/cli/tx.go
> +				fmt.Println("Error: ", err)
updated

2023-05-05 20:20 UTC, maheshKRex commented on chain/proto/empowerchain/certificates/types.proto
> +  repeated string allowed_issuer = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
yes. renamed

2023-05-05 20:20 UTC, maheshKRex commented on chain/proto/empowerchain/certificates/query.proto
> +    option (google.api.http).get = "/EmpowerPlastic/empowerchain/certificates/{id}/{owner}";
updated.

2023-05-06 20:19 UTC, gjermundgaraba commented on chain/x/certificates/keeper/certificate.go
> +func (k Keeper) CreateCertificateInternal(ctx sdk.Context, req *certificates.MsgCreateCertificate) (uint64, error) {
Hmm, maybe even better to have one that is called createCertificateFromAllowedIssuers and another just createCertificate. Or the other way around createCertificate (which checks allowed issuers) and one that says createCertificateSkipAllowedIssuers. Or something.
Got any good name ideas @maheshKRex  @ba1ciu

2023-05-08 06:32 UTC, maheshKRex commented on chain/x/certificates/keeper/certificate.go
> +func (k Keeper) CreateCertificateInternal(ctx sdk.Context, req *certificates.MsgCreateCertificate) (uint64, error) {
updated.

2023-05-08 09:02 UTC, gjermundgaraba approved these changes

2023-05-08 12:23 UTC, ba1ciu requested changes

2023-05-08 12:23 UTC, ba1ciu commented on chain/x/certificates/msgs.go
> +	return []sdk.AccAddress{owner}
```suggestion
func (m *MsgCreateCertificate) GetSigners() []sdk.AccAddress {
	issuer, err := sdk.AccAddressFromBech32(m.Issuer)
	if err != nil {
		panic(err)
	}
	return []sdk.AccAddress{issuer}
```
Nit-pick, I know 😛

2023-05-08 12:23 UTC, ba1ciu commented on chain/x/plasticcredit/keeper/credit.go
> +func (k Keeper) retireCreditsForAddress(ctx sdk.Context, req *plasticcredit.MsgRetireCredits) (plasticcredit.CreditBalance, error) {
Why did you pass the whole Msg object here? It's a bit inconsistent with the rest of the keepers where we "unpack" Msg objects at the msg server level and pass arguments directly to the keeper.

2023-05-08 12:36 UTC, maheshKRex commented on chain/x/plasticcredit/keeper/credit.go
> +func (k Keeper) retireCreditsForAddress(ctx sdk.Context, req *plasticcredit.MsgRetireCredits) (plasticcredit.CreditBalance, error) {
after adding AdditionalData field to the certificate, we have 5 fields that need to be passed to keeper and save it there. So i thought why not pass the message itself as it has all the 5. wdyt? should we have each param passed @ba1ciu

2023-05-08 12:43 UTC, ba1ciu commented on chain/x/plasticcredit/keeper/credit.go
> +func (k Keeper) retireCreditsForAddress(ctx sdk.Context, req *plasticcredit.MsgRetireCredits) (plasticcredit.CreditBalance, error) {
I get you and it's a lot of args, but I'd still pass each separately. Msg objects shouldn't reach into Keeper imo, but let us give the final vote to @gjermundgaraba.

2023-05-08 13:25 UTC, gjermundgaraba commented on chain/x/plasticcredit/keeper/credit.go
> +func (k Keeper) retireCreditsForAddress(ctx sdk.Context, req *plasticcredit.MsgRetireCredits) (plasticcredit.CreditBalance, error) {
I have to agree with Jacob on this one. While I don't like all the args, the keeper should in "theory" not know about msgs. 5 arg function ftw :D

2023-05-08 14:04 UTC, ba1ciu approved these changes

2023-05-08 15:00 UTC, merged