Add initial validator documentation
EmpowerPlastic/empowerchain pull request #625
Opened 2023-04-20 16:42 UTC by Relyte

This PR is still a work in progress, so I've marked it as a draft PR for now. I will continue working on this throughout the week/weekend to get it cleaned up and add some of the TODO sections, but I wanted to start getting feedback on it now in case there are large aspects that the team would like changed. Some links to the Empowerchain repo are assumed to exist once the testnet is live/preparing to go live, but can be modified as needed to point to their proper location.

2023-04-20 20:06 UTC, gjermundgaraba commented
@Relyte this is looking good already! Very cool to get this sorted. I looped in @ba1ciu as well who is our resident validator expert as well to chime in and give feedback.

2023-04-22 17:04 UTC, ba1ciu requested changes
Great work @Relyte and thank you! 🚀 🔥 
I fixed few typos along the way and suggested some changes.

2023-04-22 19:54 UTC, Relyte commented on docs/validators/full-node-setup.md
> +### Golang
I'll look into it and write up a section on it.

2023-04-28 09:27 UTC, gjermundgaraba commented
No worries @Relyte, very happy for the contribution :rocket:

2023-05-01 19:45 UTC, Relyte commented on docs/validators/full-node-setup.md
> +### Golang
I took a look at this over the weekend and should have a section for setting up `gvm` added to the docs soon.

2023-05-04 07:36 UTC, gjermundgaraba commented on docs/validators/full-node-setup.md
> +TODO
We might be asking other validators to help us with that. Not sure just yet. Thoughts @ba1ciu?

2023-05-12 16:10 UTC, Relyte commented on docs/validators/full-node-setup.md
> +TODO
I've added some initial instructions for snapshots/state sync. For the testnet we could add more explicit instructions on how to use the dev team's state sync if you have that on hand. For snapshots, I kept it vague since each snapshot provider typically has slightly different instructions on how to use their snapshots based on how they compress and archive them.

2023-05-15 09:02 UTC, gjermundgaraba approved these changes

2023-05-15 15:03 UTC, ba1ciu approved these changes

2023-05-15 15:04 UTC, merged