511 string to hash
EmpowerPlastic/empowerchain pull request #626
Opened 2023-04-22 06:48 UTC by PiranavanShanmugavadivelu

2023-04-25 07:50 UTC, ba1ciu requested changes

2023-04-25 07:50 UTC, ba1ciu commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +    userInput = userInput.replace(/ +/g, "");
You're replacing only spaces here. Use `\s` to get rid of all whitespace characters.

2023-04-26 05:00 UTC, PiranavanShanmugavadivelu commented on frontend/proof-of-existence/src/views/certify/CertifyView.vue
> +    userInput = userInput.replace(/ +/g, "");
Thank you , In my case It is missing new lines

2023-04-26 07:43 UTC, ba1ciu approved these changes

2023-04-28 09:19 UTC, gjermundgaraba approved these changes

2023-04-28 09:19 UTC, merged