654 my credits page pc m 5
EmpowerPlastic/empowerchain pull request #671
Opened 2023-05-04 17:06 UTC by PiranavanShanmugavadivelu

2023-05-05 18:28 UTC, gjermundgaraba approved these changes

2023-05-08 08:01 UTC, jschill requested changes

2023-05-08 08:01 UTC, jschill commented on frontend/marketplace/src/components/CreditCard.vue
> +            </button>
Two buttons with the same style calls for a <Button /> 😄

2023-05-08 12:11 UTC, ba1ciu requested changes
I think we should already build it dynamically - not hardcode values into HTML, like hardcoded pagination in `MyCredits.vue` or the data on `CreditCard.vue`, but instead read it from variables and iterate if necessary.

2023-05-09 06:22 UTC, jschill commented on frontend/marketplace/src/components/NavBar.vue
> +.nav-dropdown-button{
Nice!

2023-05-09 06:23 UTC, jschill commented on frontend/marketplace/src/components/NavBar.vue
> +                  <Button
There is no Burton or is it registered globally?

2023-05-15 09:43 UTC, merged