655 credit retirement screen pc m 6
EmpowerPlastic/empowerchain pull request #673
Opened 2023-05-06 17:16 UTC by PiranavanShanmugavadivelu

2023-05-07 16:21 UTC, gjermundgaraba approved these changes

2023-05-08 07:36 UTC, jschill requested changes

2023-05-08 07:36 UTC, jschill commented on frontend/marketplace/src/components/RetireCreditsModal.vue
> +        </div>
To avoid the repetition here, how about extracting this into a `<FormControl>` component where you can pass `label` and `placeholder` to it?

So the end would look like this:
```ts
<FormControl label="How many Plastic credits do you want to retire?" placeholder="0.01"/>
<FormControl label="Available credits in your account" placeholder="0.01"/>
```

2023-05-08 12:06 UTC, ba1ciu reviewed
Other than @jschill's comments, lgtm!

2023-05-10 06:05 UTC, PiranavanShanmugavadivelu commented on frontend/marketplace/src/components/RetireCreditsModal.vue
> +        </div>
Some styles different for these two inputs so reused the styles without creating a new component

2023-05-10 07:25 UTC, jschill requested changes

2023-05-10 07:25 UTC, jschill commented on frontend/marketplace/src/components/RetireCreditsModal.vue
> +          <label class="label">
`for` attribute missing, since its not wrapping an input

2023-05-10 07:25 UTC, jschill commented on frontend/marketplace/src/components/RetireCreditsModal.vue
> +          <label class="label">
`for` attribute missing, since its not wrapping an input

2023-05-10 07:35 UTC, jschill commented on frontend/marketplace/src/components/RetireCreditsModal.vue
> +        </div>
If its not gonna be used somewhere else i guess its ok, but if its a component that is gonna be used in many places id vote for passing in the classes that differ as an object on a case-by-case basis. 

```ts

const mpwrInputCustomClass = {
  wrappingLabel: 'border-dashed border-[1px] border-dashedBorderBlack',
  standaloneLabel: '...',
  input: '...'
}

<FormControl
  label="Available credits in your account"
  placeholder="0.01"
  :customClass="mpwrInputCustomClass"
/>
```

I really liked the way we could group classes though, and maybe that could be abstracted into another layer, like a css/custom.css files or something so its globally reached - when needed.

2023-05-15 09:45 UTC, gjermundgaraba requested changes
@PiranavanShanmugavadivelu some changes left to be fixed + conflict with main branch now, please resolve

2023-05-15 09:58 UTC, PiranavanShanmugavadivelu commented
> @PiranavanShanmugavadivelu some changes left to be fixed + conflict with main branch now, please resolve

Done

2023-05-15 10:26 UTC, merged