POE Front end fixes
EmpowerPlastic/empowerchain pull request #813
Opened 2023-06-03 20:28 UTC by PiranavanShanmugavadivelu

2023-06-04 07:55 UTC, gjermundgaraba requested changes

2023-06-04 07:55 UTC, gjermundgaraba commented on frontend/proof-of-existence/src/views/certify/CreateProofView.vue
> +  } catch (error) {
You need to check if this error is that particular error, if not we just show the error's message.

2023-06-05 11:26 UTC, gjermundgaraba commented on frontend/proof-of-existence/src/views/certify/CreateProofView.vue
> +  } catch (error) {
I'm merging this because I need the code changes for some small updates I am doing myself. Can you please open a separate PR to fix this part?

2023-06-05 11:26 UTC, merged

2023-06-05 15:25 UTC, PiranavanShanmugavadivelu commented on frontend/proof-of-existence/src/views/certify/CreateProofView.vue
> +  } catch (error) {
Sure