Update (AM Solutions) resources.md
EmpowerPlastic/empowerchain pull request #864
Opened 2023-06-10 09:04 UTC by AlexToTheMoon

2023-06-11 15:26 UTC, gjermundgaraba commented on docs/testnet/resources.md
> +| AM Solutions | Node resources (instructions, state sync, peers, seeds, genesis, etc)                        | https://www.theamsolutions.info/empowerchain
I think you are missing the last `|` here, please correct and I will merge it :)

2023-06-11 15:27 UTC, gjermundgaraba requested changes
Just a small fix needed. Also I might merge in other services in the meantime, so make sure to update and merge any updates :)

2023-06-11 19:15 UTC, AlexToTheMoon commented
Oh yeah, thanks, done !

вс, 11 июн. 2023 г., 18:26 Gjermund Garaba ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In docs/testnet/resources.md
> <https://github.com/EmpowerPlastic/empowerchain/pull/864#discussion_r1225845988>
> :
>
> > @@ -17,6 +17,7 @@ If you want to add your resource to this page, please create a PR with the chang
>  | NodeStake  | Node resources (instructions, state sync, peers, seeds, genesis, etc)                        | https://nodestake.top/empower                                                        |
>  | KonsorTech | Node resources (instructions, state sync, peers, seeds, genesis, etc)                        | https://konsortech.xyz/testnet/empower                                               |
>  | AutoStake  | Node resources ( snapshots, state sync, peers, seeds, etc)                                   | https://autostake.com/networks/testnets/empower/#services                            |
> +| AM Solutions | Node resources (instructions, state sync, peers, seeds, genesis, etc)                        | https://www.theamsolutions.info/empowerchain
>
> I think you are missing the last | here, please correct and I will merge
> it :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EmpowerPlastic/empowerchain/pull/864#pullrequestreview-1473740485>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU6WLXTBRRVII34RECT2HXDXKXPUHANCNFSM6AAAAAAZBRYFHY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-12 08:42 UTC, gjermundgaraba approved these changes

2023-06-12 08:44 UTC, merged